# Generated by Django 5.0.4 on 2024-06-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_image',
            field=models.ImageField(default='Null', upload_to='default_image/'),
        ),
    ]
