# Generated by Django 5.0.4 on 2024-06-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_default_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(default='Null', upload_to='about/')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(default='Null', upload_to='skill_image/'),
        ),
    ]
